services:
  api:
    build: .
    container_name: treeleaf
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - node.name=treeleaf
      - discovery.type=single-node
      - cluster.name = es_cluster
      - ELASTIC_PASSWORD=elasticsearch123
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled = false
      - cluster.routing.allocation.disk.threshold_enabled=false   

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
volumes:
  es_data: